import Sidebar from "@/components/Shared/Sidebar";

export const metadata = {
  title: "Nextjs Dashboard",
  description: "Generated by create next app",
};

const DashboardLoayout = ({ children }) => {
  return (
    <div className="flex">
      <Sidebar></Sidebar>
      <div className="w-full">{children}</div>
    </div>
  );
};

export default DashboardLoayout;
